export const ShellMFEPaths = {
    root: 'ShellMFE',
    pre: "app",
    paths: {
        './services': './app/internal/services',
        './services/order/queries': './app/services/order/queries',
        './internal/uiComponents': './app/internal/uiComponents',
        './envUtils': './app/utils/envUtil',
        './shared': './app/shared',
        './internal/services/api/apiService': './app/internal/services/api/apiService',
        './internal/services/api/gqlClient': './app/internal/services/api/gqlClient',
        './internal/middleware': './app/internal/middleware',
        './internal/services/tealium/order/checkoutTealiumService':
          './app/internal/services/tealium/order/checkoutTealiumService',
        './internal/middleware/tealium': './app/internal/middleware/tealium',
        './internal/utils/baseModel': './app/internal/utils/baseModel',
        './internal/services/router/router': './app/internal/services/router/router',
        './modules/shared': './app/modules/shared',
        './auth/selector': './app/modules/auth/selector',
        './auth/effects': './app/modules/auth/effects',
        './auth/actions': './app/modules/auth/actions',
        './auth/reducer': './app/modules/auth/reducer',
        './auth/handler': './app/modules/auth/handler',
        './auth/context': './app/internal/middleware/authContext',
        './actions': './app/internal/actions',
        './handlers': './app/internal/module/handlers',
        './order/effects.order': './app/modules/order/effects/effects.order',
        './order/constants': './app/modules/order/constants',
        './order/commonUtils': './app/modules/order/utils/commonUtils',
        './order/selectors': './app/modules/order/selectors',
        './order/selectors.order': './app/modules/order/selectors/selectors.order',
        './order/lineItemUtils': './app/modules/order/utils/lineItemUtils',
        './order/pricingUtils': './app/modules/order/utils/pricingUtils',
        './order/substituteItemUtils': './app/modules/order/utils/substituteItemUtils',
        './order/messages': './app/modules/order/messages',
        './layout/constants': './app/modules/layout/constants',
        './layout/messages': './app/modules/layout/messages',
        './accountManager/constants': './app/modules/accountManager/constants',
        // './catalog/constants': './app/modules/catalog/constants',
        // './catalog/utils': './app/modules/catalog/utils',
        // './catalog/messages': './app/modules/catalog/messages',
        // './catalog/actions': './app/modules/catalog/actions',
        // './catalog/selectors': './app/modules/catalog/selectors',
        // './catalog/services/personalization': './app/modules/catalog/services/personalization',
        './catalog/constants': './app/modules/catalog/constants',
        './catalog/utils': './app/modules/catalog/utils',
        './catalog/messages': './app/modules/catalog/messages',
        './catalog/actions': './app/modules/catalog/actions',
        './catalog/selectors': './app/modules/catalog/selectors',
        './catalog/services/personalization': './app/modules/catalog/services/personalization',
        // './catalog/SearchProductCardLoader': './app/modules/catalog/components/SearchResults/SearchProductCardLoader',
        './dashboard/selectors': './app/modules/dashboard/selectors',
        './dashboard/services': './app/modules/dashboard/services',
        './dashboard/effects': './app/modules/dashboard/effects',
        './dashboard/actions': './app/modules/dashboard/actions',
        './dashboard/SuggestedSearches': './app/modules/dashboard/components/SuggestedSearches',
        './myProducts/messages': './app/modules/myProducts/messages',
        './myProducts/utils': './app/modules/myProducts/utils',
        './myProducts/selectors': './app/modules/myProducts/selectors',
        './myProducts/constants': './app/modules/myProducts/constants',
        './myProducts/actions': './app/modules/myProducts/actions',
        './delivery/utils': './app/modules/delivery/utils',
        './delivery/ProductItem': './app/modules/delivery/components/DeliveryProducts/ProductItem',
        './delivery/ProductCategoryHeader': './app/modules/delivery/components/DeliveryProducts/ProductCategoryHeader',
        './delivery/DeliveryError': './app/modules/delivery/components/DeliveryError',
        './deliveryForm/constants/tealiumEventTypes': './app/modules/deliveryForm/constants/tealiumEventTypes',
        './productDetails/productRoutes': './app/modules/productDetails/routes',
        './productDetails/utils': './app/modules/productDetails/utils',
        './productDetails/constants': './app/modules/productDetails/constants',
        './productDetails/services': './app/modules/productDetails/services',
        './productDetails/selectors': './app/modules/productDetails/selectors',
        './productDetails/styles': './app/modules/productDetails/styles',
        './productDetails/specs/constants': './app/modules/productDetails/components/ProductSpecs/constants',
        './order/deliveryDateUtils': './app/modules/order/utils/deliveryDateUtils',
        './order/brandConversionsUtils': './app/modules/order/utils/brandConversionsUtils',
        './order/orderSummaryUtils': './app/modules/order/utils/orderSummaryUtils',
        './order/multiApproverUtils': './app/modules/order/utils/multiApproverUtils',
        './order/keyboardNavigationUtils': './app/modules/order/utils/keyboardNavigationUtils',
        './order/quantityInputUtils': './app/modules/order/utils/quantityInputUtils',
        './order/validations': './app/modules/order/effects/validations',
        './orders/selectors': './app/modules/orders/selectors',
        './perksProgram/constants/tealiumEventTypes': './app/modules/perksProgram/constants/tealiumEventTypes',
        './settings/constants': './app/modules/settings/constants',
        './productDetails/analytics/events': './app/modules/productDetails/analytics/events',
        './productDetails/actions': './app/modules/productDetails/actions',
        './productDetails/messages': './app/modules/productDetails/messages',
        './productDetails/FPNProductFactoryPlatform':
          './app/modules/productDetails/services/product/factory/FPNProductFactoryPlatform',
        './productDetails/components/NutritionInfo': './app/modules/productDetails/components/NutritionInfo',
        './productDetails/components/Description': './app/modules/productDetails/components/Description',
        './productDetails/components/Disclaimer': './app/modules/productDetails/components/Disclaimer',
        './productDetails/components/ProductSpecs': './app/modules/productDetails/components/ProductSpecs',
        './productDetails/components/ProductImage': './app/modules/productDetails/components/ProductImage',
        './productDetails/components/HeaderInfo': './app/modules/productDetails/components/HeaderInfo',
        './productDetails/components/ProductAvailabilityDetailTable':
          './app/modules/productDetails/components/ProductAvailabilityDetailTable',
        './productDetails/components/SCInformation': './app/modules/productDetails/components/SCInformation',
        './productDetails/components/SCInformation/asoh': './app/modules/productDetails/components/SCInformation/asoh',
        './productDetails/components/SCInformation/priceCalculations':
          './app/modules/productDetails/components/SCInformation/priceCalculations',
        './productDetails/components/IncorrectProductInfo/IncorrectProductInfoWrapper':
          './app/modules/productDetails/components/IncorrectProductInfo/IncorrectProductInfoWrapper',
        './system/constants': './app/modules/system/constants',
        './system/actions': './app/modules/system/actions',
        './system/effects': './app/modules/system/effects',
        './system/selectors': './app/modules/system/selectors',
        './order/actions': './app/modules/order/actions',
        './order/components/shared/SuggestedOrderCard/ProductImage':
          './app/modules/order/components/shared/SuggestedOrderCard/ProductImage',
        './order/components/shared/Foundation/gridTemplates/columnTemplates/ProductDetailsTemplate/ProductLabelsTemplate':
          './app/modules/order/components/shared/Foundation/gridTemplates/columnTemplates/ProductDetailsTemplate/ProductLabelsTemplate',
        './order/components/shared/Foundation/QuantityPriceGroup/QuantityInput':
          './app/modules/order/components/shared/Foundation/QuantityPriceGroup/QuantityInput',
        './order/components/ReorderWidget': './app/modules/order/components/ReorderWidget',
        './productDetails/__mocks__/__data__/mockData': './app/modules/productDetails/__mocks__/__data__/mockData',
        './internal/services/optimizely/optimizelyFactory': './app/internal/services/optimizely/optimizelyFactory',
        './internal/history': './app/internal/history',
        './productDetails/nutrientModel': './app/modules/productDetails/services/product/model/nutrientModel',
        './productDetails/productService': './app/modules/productDetails/services/product/productService',
        './internal/services/tealium/tealiumService': './app/internal/services/tealium/tealiumService',
        './internal/services/tealium/ordersTealiumService': './app/internal/services/tealium/ordersTealiumService',
        './order/errors': './app/modules/order/errors',
        './order/orderService': './app/modules/order/services/orderService',
        // './catalog/components/SearchResults/SearchFilterLoader':
        //   './app/modules/catalog/components/SearchResults/SearchFilterLoader',
        // './catalog/components/SearchResults/styles': './app/modules/catalog/components/SearchResults/styles',
        './accountManager/services/queries/getOrderHeadersQuery':
          './app/modules/accountManager/services/queries/getOrderHeadersQuery',
        './catalog/components/ProductCollection/ProductList/RowTemplate':
          './app/modules/catalog/components/ProductCollection/ProductList/RowTemplate',
        './myProducts/services': './app/modules/myProducts/services',
        './myProducts/utils/brandConversionsUtils': './app/modules/myProducts/utils/brandConversionsUtils',
        './myproducts/__mocks__/services': './app/modules/myProducts/__mocks__/services',
        './utils/platform-utils': './app/utils/platform-utils',
      }
}

export const CommonMFE = {
    root: "CommonMFE",
    pre: "commons",
    paths: {
        './auth': './app/modules/auth',
        './auth/selector': './app/modules/auth/selector',
        './auth/effects': './app/modules/auth/effects',
        './auth/constants': './app/modules/auth/constants',
        './auth/actions': './app/modules/auth/actions',
        './auth/reducer': './app/modules/auth/reducer',
        './auth/handler': './app/modules/auth/handler',
        './init': './app/initializer',
        './envContext': './app/context/envContext',
        './storeProvider': './app/internal/services/mfe/storeProvider',
        './services': './app/internal/services',
        './footer': './app/modules/components/Footer/Footer',
        './optimizelyConstants': './app/internal/constants/optimizelyConstants',
        './shared': './app/modules/shared',
        './shared/guestShopping': './app/modules/shared/guestShopping',
        './userContext': './app/modules/auth/utils/userContext',
        './FeaturedProductCard': './app/modules/components/FeaturedProductCard',
        './selectors': './app/modules/commons/selectors',
        './uiComponents': './app/internal/uiComponents',
        './actions': './app/internal/actions',
        './system/constants': './app/modules/system/constants',
        './system/effects': './app/modules/system/effects',
        './productDetails/utils': './app/modules/productDetails/utils',
        './order/selectors': './app/modules/order/selectors',
  
        './Banners/OneByOneBanner': './app/modules/commons/components/Banners/1x1',
        './Banners/TwoByOneBanner': './app/modules/commons/components/Banners/2x1',
        './Banners/ThreeByOneBanner': './app/modules/commons/components/Banners/3x1',
        './Banners/BecomeACustomerBanner': './app/modules/commons/components/Banners/BecomeACustomer',
        './Banners/Hero': './app/modules/commons/components/Banners/Hero',
        './Banners/PromoBannerContainer': './app/modules/commons/components/Banners/PromoBannerContainer',
  
        './BestSellerBadge': './app/modules/commons/components/BestSellerBadge',
        './CartFlyout': './app/modules/commons/components/CartFlyout',
        './DealForYouBadge': './app/modules/commons/components/DealForYouBadge',
        './DeliveryInvoiceModal': './app/modules/commons/components/DeliveryInvoiceModal',
        './DeliveryWidget': './app/modules/commons/components/DeliveryWidget',
        './DTCOffersModal': './app/modules/commons/components/DTCOffersModal',
        './ExpandedAssortmentLabel': './app/modules/commons/components/ExpandedAssortmentLabel',
        './FavoriteButton': './app/modules/commons/components/FavoriteButton',
        './FavoriteBadge': './app/modules/commons/components/FavoriteBadge',
        './FilterDropdown': './app/modules/commons/components/FilterDropdown',
        './GenericCarousel': './app/modules/commons/components/GenericCarousel',
        './LanguageSelectorModel': './app/modules/commons/components/LanguageSelectorModel',
        './NewBadge': './app/modules/commons/components/NewBadge',
        './OriginatedSourceBadge': './app/modules/commons/components/OriginatedSourceBadge/OriginatedSourceBadge',
        './PerksAccountsEnrollModal': './app/modules/commons/components/PerksAccountsEnrollModal',
        './PerksBanner': './app/modules/commons/components/PerksBanner/PerksBanner',
        './PerksEnrollmentConfirmationModal': './app/modules/commons/components/PerksEnrollmentConfirmationModal',
        './PerksEnrollmentErrorModal': './app/modules/commons/components/PerksEnrollmentErrorModal',
        './PerksInterestModal': './app/modules/commons/components/PerksInterestModal',
        './PerksSignUpBanner': './app/modules/commons/components/PerksSignUpBanner',
        './ProductBadge': './app/modules/commons/components/ProductBadge',
        './StockBadge': './app/modules/commons/components/StockBadge',
        './ProductComparisonModal': './app/modules/commons/components/ProductComparisonModal',
        './ProgressMeter': './app/modules/commons/components/ProgressMeter',
        './PromotionalBanner': './app/modules/commons/components/PromotionalBanner',
        './Recommendations/BoughtXBoughtNextScroll':
          './app/modules/commons/components/Recommendations/BoughtXBoughtNextScroll',
        './Recommendations/BuyItAgainV2': './app/modules/commons/components/Recommendations/BuyItAgainV2',
        './Recommendations/FrequentlyPurchasedNext':
          './app/modules/commons/components/Recommendations/FrequentlyPurchasedNext',
        './Recommendations/FrequentlyPurchasedTogether':
          './app/modules/commons/components/Recommendations/FrequentlyPurchasedTogether',
        './Recommendations/FrequentlyPurchasedV2':
          './app/modules/commons/components/Recommendations/FrequentlyPurchasedV2',
        './Recommendations/MoreFromBrandProducts':
          './app/modules/commons/components/Recommendations/MoreFromBrandProducts',
        './Recommendations/PopularAmongSimilarCustomersV2':
          './app/modules/commons/components/Recommendations/PopularAmongSimilarCustomersV2',
        './Recommendations/RecentlyViewedV2': './app/modules/commons/components/Recommendations/RecentlyViewedV2',
        './Recommendations/SimilarProducts': './app/modules/commons/components/Recommendations/SimilarProducts',
        './Recommendations/SimilarProducts/constants':
          './app/modules/commons/components/Recommendations/SimilarProducts/constants',
        './Recommendations/SubProducts': './app/modules/commons/components/Recommendations/SubProducts',
        './Recommendations/SuggestionsForYouV2': './app/modules/commons/components/Recommendations/SuggestionsForYouV2',
        './Recommendations/SyscoBrandsBestSellersV2':
          './app/modules/commons/components/Recommendations/SyscoBrandsBestSellersV2',
        './Recommendations/TopDeals': './app/modules/commons/components/Recommendations/TopDeals',
        './Recommendations/TopPicksV2': './app/modules/commons/components/Recommendations/TopPicksV2',
        './SearchFilter': './app/modules/commons/components/SearchFilter',
        './UtilityBar': './app/modules/commons/components/UtilityBar',
        './SpecialDeliveryModal': './app/modules/commons/components/SpecialDeliveryModal',
        './SpendBasedOfferWidget': './app/modules/commons/components/SpendBasedOfferWidget',
        './validations': './app/modules/commons/components/validations',
        './VizientBanner': './app/modules/commons/components/VizientBanner',
        './WeeklyMinimumSpendProgressTracker': './app/modules/commons/components/WeeklyMinimumSpendProgressTracker',
        './WeeklyProgressTracker': './app/modules/commons/components/WeeklyProgressTracker',
        './terms/messages': './app/modules/terms/messages',
  
        './shared/actions': './app/modules/shared/actions',
        './modules/shared/constants': './app/modules/shared/constants',
        './shared/methods': './app/modules/shared/methods',
        './shared/methods.extended': './app/modules/shared/methods.extended',
        './shared/priceCalculations': './app/modules/shared/priceCalculations',
        './shared/utils': './app/modules/shared/utils',
        './shared/discountCalculations': './app/modules/shared/discountCalculations',
        './shared/pricing': './app/modules/shared/pricing',
        './shared/subsFlyout': './app/modules/shared/subsFlyout',
        './shared/selectors': './app/modules/shared/selectors',
        './shared/services/orderService': './app/modules/shared/services/orderService',
        './shared/utils/exceptionUtils': './app/modules/shared/utils/exceptionUtils',
        './shared/selectors/selectors.exceptionsFlyout': './app/modules/shared/selectors/selectors.exceptionsFlyout',
        './shared/selectors/selectors.subsFlyout': './app/modules/shared/selectors/selectors.subsFlyout',
        './shared/handler': './app/modules/shared/handler',
        './shared/effects': './app/modules/shared/effects',
        './modules/shared/messages': './app/modules/shared/messages',
        './shared/reducer': './app/modules/shared/reducer',
        './shared/components/i18n': './app/modules/shared/components/i18n',
        './shared/components/CreditCardBanner': './app/modules/shared/components/CreditCardBanner',
        './shared/components/DeliveryDateTemplate': './app/modules/shared/components/DeliveryDateTemplate',
        './shared/components/ExceptionViewerTrigger': './app/modules/shared/components/ExceptionViewerTrigger',
        './shared/components/OrderExceptionViewer/Flyouts':
          './app/modules/shared/components/OrderExceptionViewer/Flyouts',
        './shared/components/OrderExceptionViewer': './app/modules/shared/components/OrderExceptionViewer',
        './shared/components/OrderExceptionViewer/Modals': './app/modules/shared/components/OrderExceptionViewer/Modals',
        './shared/components/OrderExceptionViewer/Modals/ModifySubsFailedModal':
          './app/modules/shared/components/OrderExceptionViewer/Modals/ModifySubsFailedModal',
        './shared/constants': './app/shared/constants',
        './shared/messages': './app/shared/messages',
        './shared/messages/ErpErrorMessages': './app/shared/messages/ErpErrorMessages',
        './shared/analytics/tealiumEvents': './app/shared/analytics/tealiumEvents',
        './schema/userTypes': './app/schema/userTypes',
        './schema/authProcess': './app/schema/authProcess',
        './schema/messageType': './app/schema/messageType',
        './schema/errors': './app/schema/errors',
        './schema/authType': './app/schema/authType',
        './schema/modal': './app/schema/modal',
        './schema/pricingType': './app/schema/pricingType',
        './schema/languageType': './app/schema/languageType',
        './schema/errors/btErrors': './app/schema/errors/btErrors',
        './utils': './app/utils',
        './utils/accountManager': './app/utils/accountManager',
        './utils/countrySelectorUtils': './app/utils/countrySelectorUtils',
        './utils/currency': './app/utils/currency',
        './utils/dateFormatUtil': './app/utils/dateFormatUtil',
        './utils/deliveryDateUtil': './app/utils/deliveryDateUtil',
        './utils/ediOrderValidations': './app/utils/ediOrderValidations',
        './utils/fileUtils': './app/utils/fileUtils',
        './utils/formatPriceForDisplay': './app/utils/formatPriceForDisplay',
        './utils/handPriceValidation': './app/utils/handPriceValidation',
        './utils/immutableUtils': './app/utils/immutableUtils',
        './utils/inputEventHandler': './app/utils/inputEventHandler',
        './utils/inputValidation': './app/utils/inputValidation',
        './utils/languageSelectorUtil': './app/utils/languageSelectorUtil',
        './utils/mixpanelHelpers': './app/utils/mixpanelHelpers',
        './utils/orderExceptionUtils': './app/utils/orderExceptionUtils',
        './utils/ordernumber': './app/utils/ordernumber',
        './utils/ordersStatus': './app/utils/ordersStatus',
        './utils/pagination': './app/utils/pagination',
        './utils/paginationUtil': './app/utils/paginationUtil',
        './utils/perksUtils': './app/utils/perksUtils',
        './utils/phoneNumberUtil': './app/utils/phoneNumberUtil',
        './utils/productSearchFilter': './app/utils/productSearchFilter',
        './utils/pushNotificationUtils': './app/utils/pushNotificationUtils',
        './utils/recordSaga': './app/utils/recordSaga',
        './utils/reorderutil': './app/utils/reorderutil',
        './utils/sameDayDelivaryEligble': './app/utils/sameDayDelivaryEligble',
        './utils/selectedFilterName': './app/utils/selectedFilterName',
        './utils/storage': './app/utils/storage',
        './utils/syscoInfoUtils': './app/utils/syscoInfoUtils',
        './utils/url': './app/utils/url',
        './utils/base64Utils': './app/utils/base64Utils',
        './utils/formatMessage': './app/utils/formatMessage',
        './utils/graphResponseMapper': './app/utils/graphResponseMapper',
        './utils/intercomSettingsUtil': './app/utils/intercomSettingsUtil',
        './utils/lineItemUtils': './app/utils/lineItemUtils',
        './utils/listValidations': './app/utils/listValidations',
        './utils/modalUtils': './app/utils/modalUtils',
        './utils/orderFiltersUtils': './app/utils/orderFiltersUtils',
        './utils/orderLastUpdated': './app/utils/orderLastUpdated',
        './utils/ResponsiveUtils': './app/utils/responsiveUtils',
  
        './commons/actions': './app/modules/commons/actions',
        './commons/services/cms': './app/modules/commons/services/cms',
        './commons/services/order': './app/modules/commons/services/order',
  
        './commons/analytics': './app/modules/commons/analytics',
        './commons/constants': './app/modules/commons/constants',
        './commons/utils': './app/modules/commons/utils',
        './commons/utils/logoutUtils': './app/modules/commons/utils/logoutUtils',
        './commons/utils/currencyHelper': './app/modules/commons/utils/currencyHelper',
        './commons/utils/expandedAssortmentCutoffTime': './app/modules/commons/utils/expandedAssortmentCutoffTime',
        './commons/utils/mixpanelHelpers': './app/modules/commons/utils/mixpanelHelpers',
        './commons/utils/productSearchFilter': './app/modules/commons/utils/productSearchFilter',
        './commons/constants/deliveryStatusTypes': './app/modules/commons/constants/deliveryStatusTypes',
        './commons/constants/reviewReactionTypes': './app/modules/commons/constants/reviewReactionTypes',
        './commons/services': './app/modules/commons/services',
        './commons/services/taxonomy': './app/modules/commons/services/taxonomy',
        './commons/services/product/constants': './app/modules/commons/services/product/constants',
        './commons/services/product/factory/factory-utils':
          './app/modules/commons/services/product/factory/factory-utils',
        './commons/services/customer': './app/modules/commons/services/customer',
        './commons/services/config': './app/modules/commons/services/config',
        './commons/services/product': './app/modules/commons/services/product',
        './commons/services/delivery': './app/modules/commons/services/delivery',
        './commons/services/productDeals': './app/modules/commons/services/productDeals',
        './commons/services/product/util': './app/modules/commons/services/product/util',
        './commons/services/productSearch': './app/modules/commons/services/productSearch',
        './commons/services/cloudPricing': './app/modules/commons/services/cloudPricing',
        './commons/services/product/factory/asohFactory': './app/modules/commons/services/product/factory/asohFactory',
        './commons/services/product/factory/asohFactoryForNonSA':
          './app/modules/commons/services/product/factory/asohFactoryForNonSA',
        './commons/services/product/queries': './app/modules/commons/services/product/queries',
        './commons/services/product/factory/SearchProductFactory':
          './app/modules/commons/services/product/factory/SearchProductFactory',
        './commons/reducer': './app/modules/commons/reducer',
        './commons/messages': './app/modules/commons/messages',
        './commons/selectors': './app/modules/commons/selectors',
        './commons/effects': './app/modules/commons/effects',
        './commons/__mocks__/commonsRecommendations': './app/modules/commons/__mocks__/commonsRecommendations',
        './commons/__mocks__/categoryPageFacets': './app/modules/commons/__mocks__/categoryPageFacets',
        './commons/services/product/factory/InventoryPromisesFactory':
          './app/modules/commons/services/product/factory/InventoryPromisesFactory',
        './components/AddToCartButton': './app/modules/components/AddToCartButton',
        './components/AddToCartWrapper': './app/modules/components/AddToCartWrapper',
        './components/AddToListDropdown': './app/modules/components/AddToListDropdown',
        './components/AddToListMenu': './app/modules/components/AddToListMenu',
        './components/AllocationAndOrdered': './app/modules/components/AllocationAndOrdered',
        './components/AvailabilityIndicator': './app/modules/components/AvailabilityIndicator',
        './components/AvailabilityIndicator/constants': './app/modules/components/AvailabilityIndicator/constants',
        './components/AvailabilityIndicator/messages': './app/modules/components/AvailabilityIndicator/messages',
        './components/AvailabilityIndicator/styles': './app/modules/components/AvailabilityIndicator/styles',
        './components/AvailabilityIndicator/utils': './app/modules/components/AvailabilityIndicator/utils',
        './components/AvailabilityIndicator/ProductCardWrapper':
          './app/modules/components/AvailabilityIndicator/Wrappers/ProductCardWrapper',
        './components/AvailabilityIndicator/ListAndCatalogWrapper':
          './app/modules/components/AvailabilityIndicator/Wrappers/ListAndCatalogWrapper',
        './components/AvailabilityIndicator/Labels/sharedLabels':
          './app/modules/components/AvailabilityIndicator/Labels/sharedLabels',
        './modules/services': './app/services',
        './services/authentication/authenticationService': './app/services/authentication/authenticationService',
        './ ': './app/services/product/factory/StockType',
        './services/order/orderService': './app/services/order/orderService',
        './services/order/__mocks__/__data__/mockData': './app/services/order/__mocks__/__data__/mockData',
        './services/order/mutations': './app/services/order/mutations',
        './services/order/mutations/deleteOrderQuery': './app/services/order/mutations/deleteOrderQuery',
        './services/order/queries': './app/services/order/queries',
        './services/order/factory/OrderGraphHeaderFactory': './app/services/order/factory/OrderGraphHeaderFactory',
        './services/order/factory/OrderGraphInputFactory': './app/services/order/factory/OrderGraphInputFactory',
        './services/order/factory/OrderGraph': './app/services/order/factory/OrderGraph',
        './services/order/factory/OrderFactoryPricingV2': './app/services/order/factory/OrderFactoryPricingV2',
        './services/order/factory/OrderFactoryPricingV1': './app/services/order/factory/OrderFactoryPricingV1',
        './services/cloudPricing/factory/cloudPricingAgreementsFactoryForMA':
          './app/services/cloudPricing/factory/cloudPricingAgreementsFactoryForMA',
        './services/catalog/catalogService': './app/services/catalog/catalogService',
        './services/categoryFacets/categoryFacetsService': './app/services/categoryFacets/categoryFacetsService',
  
        './services/product/productService': './app/services/product/productService',
        './services/product/model/extendedProductModel': './app/services/product/model/extendedProductModel',
        './services/product/mutations/priceExceptionQuery': './app/services/product/mutations/priceExceptionQuery',
        './services/product/factory/extendedProductFactoryForNonSC':
          './app/services/product/factory/extendedProductFactoryForNonSC',
        './services/product/factory/extendedProductFactoryForProductGraph':
          './app/services/product/factory/extendedProductFactoryForProductGraph',
        './services/product/__mocks__/__data__/mockData': './app/services/product/__mocks__/__data__/mockData',
  
        './services/customer/customerService': './app/services/customer/customerService',
        './services/itemPurchaseHistory/itemPurchaseHistoryService':
          './app/services/itemPurchaseHistory/itemPurchaseHistoryService',
        './services/cloudPricing/cloudPricingService': './app/services/cloudPricing/cloudPricingService',
        './services/communicator/communicatorService': './app/services/communicator/communicatorService',
        './services/productsSearch/productsSearchService': './app/services/productsSearch/productsSearchService',
        './services/productsSearch/factory/SearchProductFactory':
          './app/services/productsSearch/factory/SearchProductFactory',
        './services/config/configService': './app/services/config/configService',
        './services/user/userService': './app/services/user/userService',
        './services/system/systemService': './app/services/system/systemService',
        './services/recommendation/recommendationService': './app/services/recommendation/recommendationService',
        './services/listService': './app/services/list/__mocks__/listService',
  
        './components/Banner': './app/modules/components/Banner',
        './components/HorizontalProductCard': './app/modules/components/HorizontalProductCard',
        './components/BannerCarousel': './app/modules/components/BannerCarousel',
        './components/BannerContent': './app/modules/components/BannerContent',
        './components/ButtonGroup': './app/modules/components/ButtonGroup',
        './components/CartBadge/CartButton': './app/modules/components/CartBadge/CartButton',
        './components/CartBadge/CartSnapshotView/CartItemList/Item':
          './app/modules/components/CartBadge/CartSnapshotView/CartItemList/Item',
        './components/CartBadge/CartSnapshotView/CartItemList':
          './app/modules/components/CartBadge/CartSnapshotView/CartItemList',
        './components/CartBadge/CartSnapshotView': './app/modules/components/CartBadge/CartSnapshotView',
        './components/CartBadge': './app/modules/components/CartBadge',
        './components/CartBadge/selectors': './app/modules/components/CartBadge/selectors',
        './components/CartSummaryView': './app/modules/components/CartSummaryView',
        './components/CartSummaryView/Item': './app/modules/components/CartSummaryView/Item',
        './components/CartSummaryView/ItemList': './app/modules/components/CartSummaryView/ItemList',
        './components/CategoryImage': './app/modules/components/CategoryImage',
        './components/CollapsiblePanel': './app/modules/components/CollapsiblePanel',
        './components/CollapsibleText': './app/modules/components/CollapsibleText',
        './components/CreateListModal': './app/modules/components/CreateListModal',
        './components/CustomCategoryDropDown': './app/modules/components/CustomCategoryDropdown',
        './components/CustomerInfo': './app/modules/components/CustomerInfo',
        './components/CommissionGrid': './app/modules/components/CommissionGrid',
        './components/CustomSearchDropDown': './app/modules/components/CustomerSearchDropdown',
        './components/DynamicList': './app/modules/components/DynamicList',
        './components/DraggleWrapper': './app/modules/components/DraggleWrapper',
        './components/DiscountPricing': './app/modules/components/DiscountPricing',
        './components/DiscountPriceInfo': './app/modules/components/DiscountPriceInfo',
        './components/DiscountPricing/messages': './app/modules/components/DiscountPricing/messages',
        './components/DemandCutoffTooltip': './app/modules/components/DemandCutoffTooltip',
        './components/DiscountDealProducts/CartPageCarousel':
          './app/modules/components/DiscountDealProducts/CartPageCarousel',
        './components/DiscountDealProducts/DiscoverPageCarousel':
          './app/modules/components/DiscountDealProducts/DiscoverPageCarousel',
        './components/EditableWrapper': './app/modules/components/EditableWrapper',
        './components/Flyout': './app/modules/components/Flyout',
        './components/FeaturedDiscountPricing': './app/modules/components/FeaturedDiscountPricing',
        './components/FileSelect': './app/modules/components/FileSelect',
        './components/FoundationCard': './app/modules/components/FoundationCard',
        './components/FoundationEditableWrapper': './app/modules/components/FoundationEditableWrapper',
        './components/FoundationDropdown': './app/modules/components/FoundationDropdown',
        './components/FoundationFileSelect': './app/modules/components/FoundationFileSelect',
        './components/FeaturedProductCard/AddToCartContainer':
          './app/modules/components/FeaturedProductCard/AddToCartContainer',
        './components/FeaturedProductCard/CompositeReadOnlyPrice':
          './app/modules/components/FeaturedProductCard/CompositeReadOnlyPrice',
        './components/FeaturedProductCard/DiscountPriceContainer':
          './app/modules/components/FeaturedProductCard/DiscountPriceContainer',
        './components/FeaturedProductCard/ProductPriceContainer':
          './app/modules/components/FeaturedProductCard/ProductPriceContainer',
        './components/FeaturedProductCard/UpdatedProductCard':
          './app/modules/components/FeaturedProductCard/UpdatedProductCard',
        './components/FeaturedProductCard/utils': './app/modules/components/FeaturedProductCard/utils',
        './components/FeaturedProductCard/UpdatedProductCard/constants':
          './app/modules/components/FeaturedProductCard/UpdatedProductCard/constants',
        './components/FeaturedProductCard/UpdatedProductCard/utils':
          './app/modules/components/FeaturedProductCard/UpdatedProductCard/utils',
        './components/FeaturedProductCard/messages': './app/modules/components/FeaturedProductCard/messages',
  
        './components/TypeAhead': './app/modules/components/TypeAhead',
        './components/Toast': './app/modules/components/Toast',
        './components/Timer': './app/modules/components/Timer',
        './components/TileSlider': './app/modules/components/TileSlider',
        './components/TextArea': './app/modules/components/TextArea',
        './components/SummaryWidget': './app/modules/components/SummaryWidget',
        './components/SuggestedOrderWidget': './app/modules/components/SuggestedOrderWidget',
        './components/SubstituteFlyouts': './app/modules/components/SubstituteFlyouts',
        './components/SubNavButton': './app/modules/components/SubNavButton',
        './components/SubLevelNavigation': './app/modules/components/SubLevelNavigation',
        './components/SSDataGrid': './app/modules/components/SSDataGrid',
        './components/GlobalSearch': './app/modules/components/GlobalSearch',
        './components/ServiceErrorView': './app/modules/components/ServiceErrorView',
        './components/SequenceInput': './app/modules/components/SequenceInput',
        './components/SelectedSubstitutesWidget': './app/modules/components/SelectedSubstitutesWidget',
        './components/SectionHeading': './app/modules/components/SectionHeading',
        './components/SearchBar': './app/modules/components/SearchBar',
        './components/ScrollBar': './app/modules/components/ScrollBar',
        './components/ReplacementProductInfo': './app/modules/components/ReplacementProductInfo',
        './components/ReadOnlyPrice': './app/modules/components/ReadOnlyPrice',
        './components/QuantityInputV2': './app/modules/components/QuantityInputV2',
        './components/PurchaseHistory': './app/modules/components/PurchaseHistory',
        './components/ProductLink': './app/modules/components/ProductLink',
        './components/ProductInfo': './app/modules/components/ProductInfo',
        './components/PillsWithLink': './app/modules/components/PillsWithLink',
        './components/Pills': './app/modules/components/Pills',
        './components/SuggestedOrderWidget/OrderModal/PackDetailsTemplate':
          './app/modules/components/SuggestedOrderWidget/OrderModal/PackDetailsTemplate',
        './components/SuggestedOrderWidget/OrderModal/PriceTemplate':
          './app/modules/components/SuggestedOrderWidget/OrderModal/PriceTemplate',
        './components/SuggestedOrderWidget/OrderModal/ProductDetailsTemplate':
          './app/modules/components/SuggestedOrderWidget/OrderModal/ProductDetailsTemplate',
        './components/SuggestedOrderWidget/OrderModal/TotalPriceTemplate':
          './app/modules/components/SuggestedOrderWidget/OrderModal/TotalPriceTemplate',
        './components/SubstituteFlyouts/messages': './app/modules/components/SubstituteFlyouts/messages',
        './components/SSDataGrid/RowTemplate': './app/modules/components/SSDataGrid/RowTemplate',
        './components/SSDataGrid/GridBody': './app/modules/components/SSDataGrid/GridBody',
        './components/RecommendationCarousels/shared/CarouselSelector':
          './app/modules/components/RecommendationCarousels/shared/CarouselSelector',
        './components/RecommendationCarousels/shared/MinimalProductCard':
          './app/modules/components/RecommendationCarousels/shared/MinimalProductCard',
        './components/RecommendationCarousels/shared/PaginatedScroll':
          './app/modules/components/RecommendationCarousels/shared/PaginatedScroll',
        './components/RecommendationCarousels/shared/ScrollableCarousel':
          './app/modules/components/RecommendationCarousels/shared/ScrollableCarousel',
        './components/RecommendationCarousels/shared/utils':
          './app/modules/components/RecommendationCarousels/shared/utils',
        './components/QuickOrderEntry': './app/modules/components/QuickOrderEntry',
        './components/QuantitySelector': './app/modules/components/QuantitySelector',
        './components/OutOfStockExceptionWidget': './app/modules/components/OutOfStockExceptionWidget',
        './components/OutageWarningBanner': './app/modules/components/OutageWarningBanner',
        './components/OrderRecommendationCarousel': './app/modules/components/OrderRecommendationCarousel',
        './components/OrderFilters': './app/modules/components/OrderFilters',
        './components/FindSimilarProductsModal': './app/modules/components/FindSimilarProductsModal',
        './components/FindSimilarProductsModal/SimilarProductsCarousel':
          './app/modules/components/FindSimilarProductsModal/SimilarProductsCarousel',
        './components/Footer': './app/modules/components/Footer/Footer',
        './components/Footer/MiniFooter': './app/modules/components/Footer/MiniFooter',
        './components/FlyoutNoDataView': './app/modules/components/FlyoutNoDataView/FlyoutNoDataView',
        './components/Footer/messages': './app/modules/components/Footer/messages',
        './components/FoundationDataGrid/styles': './app/modules/components/FoundationDataGrid/styles',
        './components/OrderFilterLabels': './app/modules/components/OrderFilterLabels',
        './components/OrderException': './app/modules/components/OrderException',
        './components/NotificationBell': './app/modules/components/NotificationBell',
        './components/NoDataView': './app/modules/components/NoDataView',
        './components/NoDataView/styles': './app/modules/components/NoDataView/styles',
        './components/NewCustomerModal': './app/modules/components/NewCustomerModal',
        './components/NewCustomerBanner': './app/modules/components/NewCustomerBanner',
        './components/NavigationSidebar': './app/modules/components/NavigationSidebar',
        './components/LimitedCatalogBanner': './app/modules/components/LimitedCatalogBanner',
        './components/InvalidPage': './app/modules/components/InvalidPage',
        './components/ImportErrorWrapper': './app/modules/components/ImportErrorWrapper',
        './components/ImportErrorModal': './app/modules/components/ImportErrorModal',
        './components/HelpButton': './app/modules/components/HelpButton',
        './components/HeaderBanner': './app/modules/components/HeaderBanner',
        './components/HandPricingModal': './app/modules/components/HandPricingModal',
        './components/HandPricingInput': './app/modules/components/HandPricingInput',
        './components/GridActionsBar': './app/modules/components/GridActionsBar',
        './components/GPOIndicator': './app/modules/components/GPOIndicator',
        './services/i18n/localize': './app/internal/services/i18n/localize',
        './formatMessage': './app/internal/services/i18n/formatMessage',
        './services/i18n/localizer': './app/internal/services/i18n/localizer',
        './services/i18n/format': './app/internal/services/i18n/format',
        './constants/apiConstants': './app/internal/constants/apiConstants',
        './internal/utils': './app/internal/utils',
        './internal/services': './app/internal/services',
        './internal/utils/context': './app/internal/utils/context',
        './internal/utils/logger': './app/internal/utils/logger',
        './internal/utils/constants': './app/internal/utils/constants',
        './internal/utils/messages': './app/internal/utils/messages',
        './dashboard/constants': './app/modules/dashboard/constants',
        './internal/utils/lodash-es.custom': './app/internal/utils/lodash-es.custom',
        './internal/utils/baseModel': './app/internal/utils/baseModel',
        './internal/utils/actionCreators': './app/internal/utils/actionCreators',
        './internal/utils/autoMergeLevel1': './app/internal/utils/autoMergeLevel1',
        './internal/utils/browserClassifier': './app/internal/utils/browserClassifier',
        './internal/utils/browserLocale': './app/internal/utils/browserLocale',
        './internal/utils/cancelOnEvent': './app/internal/utils/cancelOnEvent',
        './internal/utils/getComponentName': './app/internal/utils/getComponentName',
        './internal/utils/getFormattedDeliveryDate': './app/internal/utils/getFormattedDeliveryDate',
        './internal/utils/hash': './app/internal/utils/hash',
        './internal/utils/math': './app/internal/utils/math',
        './internal/utils/modulePersistReducer': './app/internal/utils/modulePersistReducer',
        './internal/utils/persist-query-params': './app/internal/utils/persist-query-params',
        './internal/constants/cloudPricing': './app/internal/constants/cloudPricing',
        './internal/constants/gqlErrorCodes': './app/internal/constants/gqlErrorCodes',
        './internal/constants/guestConstants': './app/internal/constants/guestConstants',
        './internal/constants/mixPanelConstants': './app/internal/constants/mixPanelConstants',
        './internal/constants/mixPanelEventTypes': './app/internal/constants/mixPanelEventTypes',
        './internal/constants/tealiumConstants': './app/internal/constants/tealiumConstants',
        './internal/constants/tealiumEventTypes': './app/internal/constants/tealiumEventTypes',
        './internal/constants/systemTealimEventTypes':
          './app/internal/constants/tealiumEventTypes/systemTealimEventTypes',
        './internal/constants/substitutesTealiumEventTypes':
          './app/internal/constants/tealiumEventTypes/substitutesTealiumEventTypes',
        './internal/constants/settingsTealiumEventTypes':
          './app/internal/constants/tealiumEventTypes/settingsTealiumEventTypes',
        './internal/constants/recommendationsTealiumEventTypes':
          './app/internal/constants/tealiumEventTypes/recommendationsTealiumEventTypes',
        './internal/constants/promotionsTealiumEventTypes':
          './app/internal/constants/tealiumEventTypes/promotionsTealiumEventTypes',
        './internal/constants/invoicesTealiumEventTypes':
          './app/internal/constants/tealiumEventTypes/invoicesTealiumEventTypes',
        './internal/constants/accountManagerTealiumEventTypes':
          './app/internal/constants/tealiumEventTypes/accountManagerTealiumEventTypes',
        './internal/constants/dealsTealiumEventTypes':
          './app/internal/constants/tealiumEventTypes/dealsTealiumEventTypes',
        './internal/constants/footerTealiumEventTypes':
          './app/internal/constants/tealiumEventTypes/footerTealiumEventTypes',
        './internal/constants': './app/internal/constants',
        './internal/services/i18n/legacyLocalizer': './app/internal/services/i18n/legacyLocalizer',
  
        './__mocks__/__data__/mockData': './app/modules/components/__mocks__/__data__/mockData',
        './commons/__mocks__/services/contentServiceBannersMock':
          './app/modules/commons/__mocks__/services/contentServiceBannersMock',
        './commons/constants/categoryPageFacets': './app/modules/commons/constants/categoryPageFacets',
        './components/RecommendationCarousels/shared/ProductCard':
          './app/modules/components/RecommendationCarousels/shared/ProductCard',
        './commons/components/ProductFilter/utils': './app/modules/commons/components/ProductFilter/utils',
        './services/system/__mocks__/__data__/getVersionInfo.mock':
          './app/services/system/__mocks__/__data__/getVersionInfo.mock',
        './services/product/factory/StockType':'./app/services/product/factory/StockType',
        './ProductFilter': './app/modules/commons/components/ProductFilter',
        './commons/components/Recommendations/HighFrequencyProductsV2':
          './app/modules/commons/components/Recommendations/HighFrequencyProductsV2',
        './components/Tile': './app/modules/components/Tile',
        './components/Row': './app/modules/components/Row',
        './CategoryDeals': './app/modules/commons/components/CategoryDeals',
        // dependencies
        './react': 'react',
        './react-dom': 'react-dom',
        './react-router-dom': 'react-router-dom',
        './styled-components': 'styled-components',
        './react-redux': 'react-redux',
        './@syscolabs/cx-foundation-react': '@syscolabs/cx-foundation-react',
        './prop-types': 'prop-types',
        './@syscolabs/aura-ui-perf': '@syscolabs/aura-ui-perf',
        './date-fns': 'date-fns',
        './redux-saga': 'redux-saga',
        './redux-persist-transform-immutable': 'redux-persist-transform-immutable',
        './redux-persist': 'redux-persist',
        './lodash-es': 'lodash-es',
        './lodash': 'lodash',
        './graphql': 'graphql',
        './immutable': 'immutable',
        './react-helmet': 'react-helmet',
        './reselect': 'reselect',
        './google-libphonenumber': 'google-libphonenumber',
        './enumify': 'enumify',
        './moment': 'moment',
        './date-fns-timezone': 'date-fns-timezone',
        './cuid': 'cuid',
        './@optimizely/optimizely-sdk': '@optimizely/optimizely-sdk',
        './@datadog/browser-logs': '@datadog/browser-logs',
        './react-i18next': 'react-i18next',
        './i18next': 'i18next',
        './react-intl': 'react-intl',
        './validator/lib/isCurrency': 'validator/lib/isCurrency',
      }
}

export const replaceWithPrePath = (rootPath, prePath, exposes,) => {
    return exposes.map(path => path.replace('app', prePath))
}

export const absoluteImports = {
    'Framework/Services': 'internal/services',
    'Framework/Utils': 'internal/utils',
    'Framework/Shared': 'internal/shared',
    'Framework/Middleware': 'internal/middleware',
    'Framework/Constants': 'modules/Auth',
    'Framework/System': 'modules/system',
    'Framework/SharedUtils': '/utils',
    'Framework/Error': 'internal/containers/ErrorBoundary',
    'Modules/Shared': 'modules/shared',
    'Modules/SharedSelectors': 'modules/shared/selectors',
}

function mergePathObjects(...pathObjects) {
    const mergedPaths = {};

    pathObjects.forEach(pathObject => {
        const { root, paths, pre } = pathObject;

        for (let [key, value] of Object.entries(paths)) {
            let newKey = key.replace('.', root);

            mergedPaths[newKey] = value.replace('app', pre);
        }
    });

    return mergedPaths;
}

const mfeNames = [
    'mss-frontend',
    'cx-shop-fe-catalog'
];

export const mergedPaths = mergePathObjects(ShellMFEPaths, CommonMFE);